"✨ feature":
  - head-branch: ['^feat/']

"🐛 bug/error":
  - head-branch: ['^fix/']

"♻️ refactor":
  - head-branch: ['^refactor/']

"⚙️ chore":
  - head-branch: ['^chore/']

"📝 documentation":
  - head-branch: ['^docs/']

"🚑 hotfix":
  - head-branch: ['^hotfix/']