ALTER TABLE nodes
    ALTER COLUMN name TYPE VARCHAR(30);

ALTER TABLE nodes
    ALTER COLUMN memo TYPE VARCHAR(500);

ALTER TABLE workspaces
    ALTER COLUMN name TYPE VARCHAR(30);

ALTER TABLE folders
    ALTER COLUMN name TYPE VARCHAR(30);
